language: ruby
rvm:
  - 2.2
  - 2.3
sudo: required
dist: trusty
env: 
  - DB=mysql
  - DB=pg
services:
  - postgresql
before_install: 
  - gem install bundler
  - gem update --system
  - gem --version
before_script:
  - mysql -u root -e 'CREATE DATABASE travis_ci_test;'
  - psql -c 'create database travis_ci_test;' -U postgres
gemfile:
  - gemfiles/3.2.gemfile
  - gemfiles/4.2.gemfile
  - gemfiles/5.0.gemfile
  - gemfiles/5.1.gemfile
addons:
    code_climate:
        repo_token: 6384ecacad280dc863595e6e369a43299e157c0e7588b636e025a1808a3f5581
after_success:
  - bundle exec codeclimate-test-reporter

